services:
  database:
    container_name: database
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  broker:
    container_name: broker
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
