site_name: Документация

theme:
  name: 'material'

nav:
  - Главная: 'index.md'
  - Лабораторная работа №1:
      - База данных: 'lr_1/db.md'
      - Аутентификация: 'lr_1/auth.md'
      - Эндпоинты: 'lr_1/endpoints.md'
  - Лабораторная работа №2:
      - Задание 1: 'lr_2/task_1.md'
      - Задание 2: 'lr_2/task_2.md'
  - Лабораторная работа №3:
      - Настройка docker: 'lr_3/docker.md'
      - Настройка celery: 'lr_3/celery.md'
